"""数据库服务层入口，聚合模型与工具函数。"""
from .alias_service import (
    add_alias,
    find_play_by_alias_or_name,
    get_aliases_for_work,
    link_source,
    record_no_response,
)
from .connection import (
    DATABASE_PATH,
    DATABASE_URL,
    configure_engine,
    get_engine,
    get_session,
    set_engine,
)
from .group_service import create_group, get_groups_for_user
from .health_check import (
    check_napcat_health,
    ensure_napcat_connected,
    health_logger,
    network_logger,
)
from .init import init_db
from .models import (
    Group,
    GroupType,
    Membership,
    Play,
    PlaySnapshot,
    RoleType,
    Subscription,
    SubscriptionFrequency,
    SubscriptionOption,
    SubscriptionTarget,
    SubscriptionTargetKind,
    TimeStamped,
    User,
    UserRole,
    WeightLevel,
    WorkAlias,
    WorkSourceLink,
)
from .subscription_service import add_subscription, list_subscriptions, remove_subscription
from .user_service import add_user, get_user_by_id, update_user_activity

__all__ = [
    "DATABASE_PATH",
    "DATABASE_URL",
    "Group",
    "GroupType",
    "Membership",
    "Play",
    "PlaySnapshot",
    "RoleType",
    "Subscription",
    "SubscriptionFrequency",
    "SubscriptionOption",
    "SubscriptionTarget",
    "SubscriptionTargetKind",
    "TimeStamped",
    "User",
    "UserRole",
    "WeightLevel",
    "WorkAlias",
    "WorkSourceLink",
    "add_alias",
    "find_play_by_alias_or_name",
    "get_aliases_for_work",
    "link_source",
    "record_no_response",
    "create_group",
    "get_groups_for_user",
    "check_napcat_health",
    "ensure_napcat_connected",
    "health_logger",
    "network_logger",
    "init_db",
    "configure_engine",
    "get_engine",
    "get_session",
    "set_engine",
    "add_subscription",
    "list_subscriptions",
    "remove_subscription",
    "add_user",
    "get_user_by_id",
    "update_user_activity",
]
